"use strict";

(() => {
    const canvas = document.getElementById("longwall-canvas");
    if (!canvas) return;
    const context = canvas.getContext("2d", { alpha: false });
    const page = document.getElementById("longwall");
    const resetButton = document.getElementById("longwall-reset");
    const overviewButton = document.getElementById("longwall-overview");
    const positionReadout = document.getElementById("longwall-position-readout");
    const depthReadout = document.getElementById("longwall-depth-readout");
    const roofReadout = document.getElementById("longwall-roof-readout");
    const speedReadout = document.getElementById("longwall-speed-readout");
    const airReadout = document.getElementById("longwall-air-readout");
    const chargeReadout = document.getElementById("longwall-charge-readout");
    const chargeBar = document.getElementById("longwall-charge-bar");
    const chargeCopy = document.getElementById("longwall-charge-copy");
    const seamStatus = document.getElementById("longwall-seam-status");
    const shieldStatus = document.getElementById("longwall-shield-status");
    const cutterStatus = document.getElementById("longwall-cutter-status");
    const collapseStatus = document.getElementById("longwall-collapse-status");
    const atmosphereStatus = document.getElementById("longwall-atmosphere-status");
    const oreStatus = document.getElementById("longwall-ore-status");
    const buttons = Array.from(document.querySelectorAll("[data-longwall-control]"));

    const WIDTH = 1040, LENGTH = 8400, STARTERS = 24, RADIUS = 23, TAU = Math.PI * 2;
    const colours = ["#8b9187", "#9a745a", "#667e78", "#8c826c", "#a09983", "#6d756d", "#98624d"];
    const input = { throttle: false, brake: false, left: false, right: false };
    const world = { width: 1300, height: 920, dpr: 1, scale: .72, time: 0, lastTime: performance.now(), cameraY: 400, cameraV: 0, overview: false, result: "racing", detail: "Extraction active", collapse: -750, shake: 0, finishers: 0, eliminated: 0, particles: [], ore: [], wasVisible: false };
    const charges = [1400, 3000, 4600, 6200].map((y, index) => ({ index, y, state: "armed", timer: 0, side: index % 2 ? 1 : -1 }));
    const player = makeCar(0, -70, true, 12); let rivals = [];

    function clamp(v,a,b){return Math.max(a,Math.min(b,v));} function lerp(a,b,t){return a+(b-a)*t;} function smooth(v){const t=clamp(v,0,1);return t*t*(3-2*t);} function seeded(i,s=0){const v=Math.sin(i*94.17+s*43.71)*43758.54;return v-Math.floor(v);}
    function makeCar(x,y,isPlayer,number){return{x,y,vx:0,vy:0,heading:0,speed:0,isPlayer,number,colour:isPlayer?"#c6a44a":colours[number%colours.length],mass:isPlayer?1600:1250+seeded(number,2)*950,active:true,finished:false,finishPosition:0,falling:0,fallCause:"",dust:0,air:1,flash:0,pin:0,targetX:x,aggression:.28+seeded(number,7)*.68};}
    function all(){return[player,...rivals];} function active(){return all().filter((car)=>car.active&&!car.finished&&car.falling===0);}
    function reset(){Object.assign(player,makeCar(30,-80,true,12));rivals=[];for(let i=0;i<23;i++){const lane=i%8,row=Math.floor(i/8);rivals.push(makeCar(-370+lane*105+(seeded(i,3)-.5)*20,-row*74+(seeded(i,4)-.5)*12,false,i+1));}charges.forEach((charge)=>{charge.state="armed";charge.timer=0;});Object.assign(world,{time:0,cameraY:400,cameraV:0,overview:false,result:"racing",detail:"Extraction active",collapse:-750,shake:0,finishers:0,eliminated:0});world.particles.length=0;world.ore.length=0;Object.keys(input).forEach((key)=>{input[key]=false;});overviewButton.textContent="Survey mine";updateReadouts();render();}

    function trigger(charge){if(charge.state!=="armed")return;charge.state="fuse";charge.timer=0;burst(0,charge.y-380,10,"#d0a14d");}
    function updateMine(delta){const lead=Math.max(...active().map((car)=>car.y),player.y);charges.forEach((charge)=>{if(charge.state==="armed"&&lead>charge.y-520)trigger(charge);if(charge.state!=="fuse")return;charge.timer+=delta;if(charge.timer>2.2){charge.state="blasted";charge.timer=0;world.shake=.9;burst(charge.side*150,charge.y,40,"#9e9278");for(let i=0;i<7;i++)world.ore.push({x:charge.side*(80+seeded(i,charge.index)*330),y:charge.y+60+seeded(i,9)*360,radius:20+seeded(i,11)*35});}});world.collapse=Math.max(-750,world.time>9?(world.time-9)*59:-750);}
    function beginFall(car,cause){if(!car.active||car.finished||car.falling>0)return;car.falling=.001;car.fallCause=cause;world.eliminated+=1;if(car.isPlayer)world.detail=cause==="roof"?"Caught beneath the unsupported roof":"Lost in a blasted floor break";burst(car.x,car.y,16,"#938873");world.shake=Math.max(world.shake,car.isPlayer?1:.3);}
    function nextCharge(car){return charges.find((charge)=>car.y<charge.y+250&&charge.state!=="blasted");}
    function ai(car){let target=car.targetX;const charge=nextCharge(car);if(charge&&charge.state==="blasted")target=-charge.side*190;const ore=world.ore.find((rock)=>rock.y>car.y&&rock.y-car.y<170&&Math.abs(rock.x-car.x)<rock.radius+34);if(ore)target+=car.x<=ore.x?-125:125;const cutter=cutterPosition(car.y);if(cutter&&Math.abs(cutter.x-car.x)<100)target+=car.x<=cutter.x?-150:150;target=clamp(target,-450,450);car.targetX=target;return{throttle:.82+car.aggression*.17,brake:0,steering:clamp((target-car.x)/125-car.vx/180,-1,1)};}
    function cutterPosition(y){const zone=charges.find((charge)=>y>charge.y+280&&y<charge.y+760);if(!zone)return null;const phase=(world.time*0.72+zone.index)*TAU/6;return{x:Math.sin(phase)*340,y:zone.y+520,vx:Math.cos(phase)*245};}

    function updateCar(car,delta,controls){if(!car.active||car.finished)return;car.flash=Math.max(0,car.flash-delta*3.5);if(car.falling>0){car.falling+=delta;car.vx*=Math.pow(.07,delta);car.vy*=Math.pow(.07,delta);if(car.falling>1.12){car.active=false;if(car.isPlayer&&world.result==="racing")world.result="eliminated";}return;}
        const charge=charges.find((item)=>item.state!=="blasted"&&car.y<item.y&&item.y-car.y<90);if(charge&&car.y>charge.y-55){car.y=charge.y-55;car.vy=Math.min(0,car.vy)*.2;car.flash=1;}
        const gallery=Math.floor(Math.max(0,car.y)/800)%3;car.air=gallery===1&&Math.abs(car.x)>260?.58:1;const dusty=charges.some((item)=>item.state==="blasted"&&car.y>item.y-80&&car.y<item.y+620);if(dusty)car.dust=clamp(car.dust+delta*(controls.throttle>.5?.07:.025),0,1);else car.dust=Math.max(0,car.dust-delta*.04);const power=(1-car.dust*.52)*car.air;const grip=.91;const speed=Math.hypot(car.vx,car.vy);
        if(controls.throttle>0){const force=210/(car.mass/1600)*controls.throttle*power;car.vx+=Math.sin(car.heading)*force*delta;car.vy+=Math.cos(car.heading)*force*delta;}if(controls.brake>0&&speed>1){const next=Math.max(0,speed-245*controls.brake*delta);car.vx*=next/speed;car.vy*=next/speed;}car.heading+=controls.steering*clamp(speed/65,.14,1)*1.95*delta;const fx=Math.sin(car.heading),fy=Math.cos(car.heading),long=car.vx*fx+car.vy*fy,lat=(car.vx*fy-car.vy*fx)*Math.pow(Math.max(.03,1-grip*4.2*delta),1);car.vx=fx*long+fy*lat;car.vy=fy*long-fx*lat;const maximum=385*power+55,driven=Math.hypot(car.vx,car.vy);if(driven>maximum){car.vx*=maximum/driven;car.vy*=maximum/driven;}car.vx*=Math.pow(.991,delta*60);car.vy*=Math.pow(.991,delta*60);car.x+=car.vx*delta;car.y+=car.vy*delta;car.speed=Math.hypot(car.vx,car.vy);
        if(Math.abs(car.x)>WIDTH*.5-28){const side=Math.sign(car.x);car.x=side*(WIDTH*.5-28);car.vx*=-.3;car.flash=1;}if(car.y<world.collapse-85)beginFall(car,"roof");world.ore.forEach((rock)=>{const dx=car.x-rock.x,dy=car.y-rock.y,d=Math.hypot(dx,dy),m=rock.radius+RADIUS;if(d<m&&d>.01){const nx=dx/d,ny=dy/d;car.x+=nx*(m-d);car.y+=ny*(m-d);car.vx+=nx*25;car.vy+=ny*25;car.flash=1;}});const cutter=cutterPosition(car.y);if(cutter){const dx=car.x-cutter.x,dy=car.y-cutter.y,d=Math.hypot(dx,dy),m=68+RADIUS;if(d<m&&d>.01){const nx=dx/d,ny=dy/d;car.x+=nx*(m-d);car.y+=ny*(m-d);car.vx+=cutter.vx*.42+nx*35;car.vy+=ny*35;car.pin+=delta*.5;car.flash=1;world.shake=Math.max(world.shake,car.isPlayer?.7:.2);}}if(car.y>=LENGTH)finish(car);}
    function collisions(){const cars=active();for(let a=0;a<cars.length;a++)for(let b=a+1;b<cars.length;b++){const f=cars[a],s=cars[b],dx=s.x-f.x,dy=s.y-f.y,d=Math.hypot(dx,dy),m=RADIUS*2;if(d>=m||d<.01)continue;const nx=dx/d,ny=dy/d,o=m-d;f.x-=nx*o*.5;f.y-=ny*o*.5;s.x+=nx*o*.5;s.y+=ny*o*.5;const rel=(s.vx-f.vx)*nx+(s.vy-f.vy)*ny;if(rel<0){f.vx+=rel*nx*.55;f.vy+=rel*ny*.55;s.vx-=rel*nx*.55;s.vy-=rel*ny*.55;f.flash=s.flash=1;}}}
    function finish(car){if(car.finished)return;car.finished=true;car.active=false;world.finishers+=1;car.finishPosition=world.finishers;if(car.isPlayer){world.result="finished";world.detail=car.finishPosition===1?"First into daylight":`Finished P${car.finishPosition}`;}}
    function burst(x,y,count,colour){for(let i=0;i<count;i++){const angle=seeded(i+world.time*100,count)*TAU,speed=12+seeded(i,4)*90;world.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,radius:5+seeded(i,6)*15,life:1+seeded(i,8),max:2,colour});}if(world.particles.length>280)world.particles.splice(0,world.particles.length-280);}
    function updateParticles(delta){world.particles.forEach((p)=>{p.x+=p.vx*delta;p.y+=p.vy*delta;p.vx*=Math.pow(.1,delta);p.vy*=Math.pow(.1,delta);p.radius+=delta*5;p.life-=delta;});world.particles=world.particles.filter((p)=>p.life>0);}
    function position(){if(player.finished)return player.finishPosition;return clamp(rivals.filter((car)=>car.finished||(car.active&&car.y>player.y)).length+1,1,STARTERS);}
    function update(delta){world.time+=delta;if(world.result!=="racing"){updateParticles(delta);updateReadouts();return;}updateMine(delta);rivals.forEach((car)=>updateCar(car,delta,ai(car)));updateCar(player,delta,{throttle:input.throttle?1:0,brake:input.brake?1:0,steering:(input.left?-1:0)+(input.right?1:0)});collisions();updateParticles(delta);const target=world.overview?LENGTH*.5:player.y+390;world.cameraV+=(target-world.cameraY)*Math.min(1,delta*5);world.cameraV*=Math.pow(.004,delta);world.cameraY+=world.cameraV*delta;world.shake=Math.max(0,world.shake-delta*2);updateReadouts();}

    function scale(){return world.overview?Math.min((world.width-90)/(WIDTH+180),(world.height-70)/(LENGTH+300)):world.scale;}function point(x,y){const s=scale();return{x:world.width*.5+x*s,y:world.height*.68-(y-world.cameraY)*s};}
    function drawWorld(){context.fillStyle="#11130f";context.fillRect(0,0,world.width,world.height);const s=scale(),left=world.width*.5-WIDTH*.5*s,right=world.width*.5+WIDTH*.5*s;context.fillStyle="#3e403a";context.fillRect(left,0,right-left,world.height);const first=Math.floor((world.cameraY-world.height/s)/180)*180;for(let y=first;y<world.cameraY+world.height/s;y+=180){const p=point(0,y);context.fillStyle="rgba(199,189,162,.06)";context.fillRect(left,p.y,right-left,2);}for(let lane=-2;lane<=2;lane++){const x=point(lane*175,0).x;context.setLineDash([12,16]);context.strokeStyle="rgba(226,216,190,.13)";context.beginPath();context.moveTo(x,0);context.lineTo(x,world.height);context.stroke();}context.setLineDash([]);charges.forEach((charge)=>drawCharge(charge,left,right));world.ore.forEach((rock)=>{const p=point(rock.x,rock.y),r=rock.radius*s;context.fillStyle="#5f584a";context.beginPath();context.moveTo(p.x-r,p.y+r*.3);context.lineTo(p.x-r*.2,p.y-r);context.lineTo(p.x+r,p.y-r*.1);context.lineTo(p.x+r*.5,p.y+r);context.closePath();context.fill();context.strokeStyle="#988b70";context.stroke();});const roof=point(0,world.collapse);context.fillStyle="rgba(20,17,14,.91)";context.fillRect(left,roof.y,right-left,world.height-roof.y);context.strokeStyle="#bd5941";context.lineWidth=3;context.beginPath();context.moveTo(left,roof.y);context.lineTo(right,roof.y);context.stroke();for(let i=0;i<7;i++){const x=lerp(left,right,i/6);context.fillStyle="#817b69";context.fillRect(x-7,roof.y-28,14,28);}const finish=point(0,LENGTH);context.fillStyle="#d9d3c0";context.fillRect(left,finish.y-9,right-left,18);}
    function drawCharge(charge,left,right){const p=point(0,charge.y),s=scale();context.fillStyle="rgba(17,15,12,.78)";context.fillRect(left,p.y-20,right-left,40);if(charge.state!=="blasted"){const gapCenter=world.width*.5+charge.side*190*s;context.fillStyle="#766b59";context.fillRect(left,p.y-22,right-left,44);context.fillStyle="#151713";context.fillRect(gapCenter-34*s,p.y-24,68*s,48);context.strokeStyle="#b8543e";context.lineWidth=2;context.strokeRect(gapCenter-34*s,p.y-24,68*s,48);}if(charge.state==="fuse"){const progress=clamp(charge.timer/2.2,0,1);context.strokeStyle="#daa64d";context.lineWidth=4;context.beginPath();context.moveTo(left,p.y-36);context.lineTo(lerp(left,right,progress),p.y-36);context.stroke();}const cutter=cutterPosition(charge.y+520);if(cutter){const cp=point(cutter.x,cutter.y),r=66*s;context.fillStyle="#777267";context.beginPath();context.arc(cp.x,cp.y,r,0,TAU);context.fill();context.strokeStyle="#b9ae91";context.lineWidth=3;context.stroke();for(let i=0;i<8;i++){const a=i/8*TAU+world.time;context.beginPath();context.moveTo(cp.x,cp.y);context.lineTo(cp.x+Math.cos(a)*r,cp.y+Math.sin(a)*r);context.stroke();}}}
    function drawCar(car){if(!car.active&&!car.finished)return;const p=point(car.x,car.y);if(p.y<-80||p.y>world.height+80)return;const s=scale(),fall=car.falling?clamp(car.falling/1.12,0,1):0;context.save();context.translate(p.x,p.y+fall*25);context.rotate(car.heading);context.globalAlpha=1-fall*.75;context.fillStyle="rgba(0,0,0,.36)";context.fillRect(-16*s+4,-29*s+6,32*s,58*s);context.fillStyle=car.flash>0?"#e0d5b4":car.colour;context.fillRect(-16*s,-29*s,32*s,58*s);context.fillStyle="#1e231e";context.fillRect(-11*s,-10*s,22*s,21*s);context.strokeStyle=car.isPlayer?"#efdb9e":"rgba(233,228,210,.48)";context.lineWidth=car.isPlayer?2:1;context.strokeRect(-16*s,-29*s,32*s,58*s);context.restore();}
    function drawParticles(){world.particles.forEach((p)=>{const q=point(p.x,p.y);context.globalAlpha=clamp(p.life/p.max,0,1)*.4;context.fillStyle=p.colour;context.beginPath();context.arc(q.x,q.y,p.radius*scale(),0,TAU);context.fill();});context.globalAlpha=1;}
    function render(){const sx=(seeded(Math.floor(world.time*73),3)-.5)*world.shake*7;context.setTransform(world.dpr,0,0,world.dpr,sx*world.dpr,0);context.clearRect(-20,-20,world.width+40,world.height+40);drawWorld();all().slice().sort((a,b)=>b.y-a.y).forEach(drawCar);drawParticles();if(world.result!=="racing"){context.fillStyle="rgba(5,6,5,.72)";context.fillRect(0,0,world.width,world.height);context.fillStyle="#eee8da";context.font="500 40px Clash Display";context.textAlign="center";context.fillText(world.result==="finished"?"DAYLIGHT SECURED":"THE ROOF CLOSED",world.width/2,world.height/2);}}

    function upcoming(){return charges.find((charge)=>player.y<charge.y+200&&charge.state!=="blasted")||charges[charges.length-1];}
    function updateReadouts(){const charge=upcoming();positionReadout.textContent=`${position()} / ${STARTERS}`;depthReadout.textContent=`−${Math.max(0,Math.round(620-player.y/LENGTH*590))} m`;roofReadout.textContent=player.y-world.collapse<500?"Collapse near":"Supported";speedReadout.textContent=`${Math.round(player.speed*.36)} km/h`;airReadout.textContent=world.result!=="racing"?world.detail:player.air<.8?"Oxygen poor":player.dust>.55?"Intake choking":player.dust>.2?"Dust loading":"Clear";chargeReadout.textContent=`Seam ${String.fromCharCode(65+charge.index)} / ${charge.state}`;const progress=charge.state==="fuse"?charge.timer/2.2:charge.state==="blasted"?1:0;chargeBar.style.width=`${clamp(progress*100,0,100)}%`;chargeCopy.textContent=charge.state==="fuse"?`Detonation in ${Math.max(0,2.2-charge.timer).toFixed(1)} seconds`:charge.state==="blasted"?"Heading opened":"Cross the trip line to open the heading";seamStatus.textContent=`${charges.filter((item)=>item.state==="armed").length} charge lines armed`;shieldStatus.textContent=player.y-world.collapse<600?"Support window closing":"Supports advancing";cutterStatus.textContent=Math.sin(world.time*.72)>=0?"Face moving east":"Face moving west";collapseStatus.textContent=`Roof at ${Math.max(0,Math.round(world.collapse))} m`;atmosphereStatus.textContent=player.air<.8?"Dead heading / low oxygen":player.dust>.4?"Silica load increasing":"Ventilation active";oreStatus.textContent=`${world.ore.length} persistent fragments`;}
    function resize(){const width=Math.max(1,canvas.clientWidth||1300),height=Math.max(1,canvas.clientHeight||920);world.dpr=Math.min(window.devicePixelRatio||1,2);world.width=width;world.height=height;world.scale=clamp(Math.min(width/1550,height/1200),.5,.84);canvas.width=Math.round(width*world.dpr);canvas.height=Math.round(height*world.dpr);render();}
    const keyMap={w:"throttle",arrowup:"throttle",s:"brake",arrowdown:"brake",a:"left",arrowleft:"left",d:"right",arrowright:"right"};function setControl(name,on){if(!(name in input))return;input[name]=on;buttons.forEach((button)=>{if(button.dataset.longwallControl===name)button.classList.toggle("is-pressed",on);});}window.addEventListener("keydown",(event)=>{const name=keyMap[event.key.toLowerCase()];if(!name||page.hidden)return;event.preventDefault();setControl(name,true);});window.addEventListener("keyup",(event)=>{const name=keyMap[event.key.toLowerCase()];if(name)setControl(name,false);});window.addEventListener("blur",()=>Object.keys(input).forEach((name)=>setControl(name,false)));buttons.forEach((button)=>{const name=button.dataset.longwallControl;const down=(event)=>{event.preventDefault();setControl(name,true);};const up=(event)=>{event.preventDefault();setControl(name,false);};button.addEventListener("pointerdown",down);button.addEventListener("pointerup",up);button.addEventListener("pointercancel",up);});resetButton.addEventListener("click",reset);overviewButton.addEventListener("click",()=>{world.overview=!world.overview;overviewButton.textContent=world.overview?"Follow vehicle":"Survey mine";});
    reset();function animate(time){const delta=Math.min(.04,Math.max(0,(time-world.lastTime)/1000));world.lastTime=time;const visible=!page.hidden&&document.visibilityState!=="hidden";if(visible){world.wasVisible=true;update(delta);render();}else if(world.wasVisible){world.wasVisible=false;world.lastTime=time;}requestAnimationFrame(animate);}if(typeof ResizeObserver!=="undefined")new ResizeObserver(resize).observe(canvas);else window.addEventListener("resize",resize);
    window.longwall={resize,reset,setControl,diagnostics:()=>({result:world.result,detail:world.detail,time:world.time,collapse:world.collapse,player:{x:player.x,y:player.y,vx:player.vx,vy:player.vy,speed:player.speed,heading:player.heading,active:player.active,falling:player.falling,position:position(),dust:player.dust,air:player.air},finishers:world.finishers,eliminated:world.eliminated,charges:charges.map((charge)=>({state:charge.state,timer:charge.timer})),ore:world.ore.length})};requestAnimationFrame(animate);
})();
