#include "Kernel/BlendSolver.h"
#include "Console/ConsoleHost.h"
#include "VerificationPanel.h"
#include <cmath>
#include <filesystem>
using namespace Frontier;
namespace { int FaceAt(const BrepBody& B,double z){for(size_t i=0;i<B.Faces.size();++i)if(B.Faces[i].Surface.Classification==SurfaceClassification::Plane){auto&s=B.Faces[i].Surface; if(std::fabs(s.Sample(.5*(s.DomainStartU()+s.DomainEndU()),.5*(s.DomainStartV()+s.DomainEndV())).Z-z)<1e-8)return int(i);}return -1;} bool Cone(const BrepBody&B,double r0,double r1,double h){if(!B.Validate().Solid()||B.Faces.size()!=3)return false;for(auto&f:B.Faces)if(f.Surface.Classification==SurfaceClassification::Cone)return std::fabs(f.Surface.RadiusMajor-r0)<1e-10&&std::fabs(f.Surface.RadiusMinor-r1)<1e-10;return false;}}
int main(){VerificationPanel P("SolidArc · Phase 30 · Cone Cap Push Verification — exact cap-face offsets");auto B=BrepBody::Cone({0,0,0},{0,0,1},10,4,20).Payload;int Lo=FaceAt(B,0),Hi=FaceAt(B,20);P.Section("Exact supporting-cone cap moves");P.Expect("Native frustum exposes both planar caps",Lo>=0&&Hi>=0);auto T=BlendSolver::PushFace(B,Hi,2),L=BlendSolver::PushFace(B,Lo,2),Ti=BlendSolver::PushFace(B,Hi,-2),Li=BlendSolver::PushFace(B,Lo,-2);P.Expect("Upper outward push is exact 10→3.4 over height 22",T&&Cone(T.Payload,10,3.4,22));P.Expect("Lower outward push is exact 10.6→4 over height 22",L&&Cone(L.Payload,10.6,4,22));P.Expect("Upper inward push is exact 10→4.6 over height 18",Ti&&Cone(Ti.Payload,10,4.6,18));P.Expect("Lower inward push is exact 9.4→4 over height 18",Li&&Cone(Li.Payload,9.4,4,18));P.Expect("Over-collapse height refuses",!BlendSolver::PushFace(B,Hi,-20));
#ifndef SOLIDARC_PROOF_FOLDER
#error proof folder required
#endif
P.Section("C++ visual proof");std::filesystem::path Q=std::filesystem::path(SOLIDARC_PROOF_FOLDER)/"Phase30_ConeCapPushes.png";std::error_code E;std::filesystem::remove(Q,E);ConsoleHost H(SOLIDARC_PROOF_FOLDER,1280,800);auto R=[&](const char*s){return H.Execute(s);};bool ok=R("gizmo off")&&R("reset")&&R("view iso")&&R("cone (-15,0,0) 8 3 20 --name=Ref")&&R("matcap Ref steel")&&R("cone (15,0,0) 8 3 20 --name=Src")&&R("push Src 4 --face=2 --name=Top")&&R("matcap Top gold")&&R("view fit")&&R("render sheet 0")&&R("reset")&&R("view iso")&&R("cone (-15,0,0) 8 3 20 --name=Ref")&&R("matcap Ref steel")&&R("cone (15,0,0) 8 3 20 --name=Src")&&R("push Src 4 --face=1 --name=Bottom")&&R("matcap Bottom plastic-blue")&&R("view fit")&&R("render sheet 1")&&R("reset")&&R("view iso")&&R("cone (-15,0,0) 8 3 20 --name=Ref")&&R("matcap Ref steel")&&R("cone (15,0,0) 8 3 20 --name=Src")&&R("push Src -8 --face=2 --name=Inset")&&R("matcap Inset copper")&&R("view fit")&&R("render sheet 2")&&R("render sheet finalize Phase30_ConeCapPushes");P.Expect("C++ proof commands complete",ok);P.Expect("C++ proof exists",std::filesystem::exists(Q)&&std::filesystem::file_size(Q,E)>100000);return P.Conclude();}
